### ISSUE TITLE
First user or sample data

### ISSUE THREAD

**Issue by oterox** [SohanChy/Simple-Laravel-REST-API-Boilerplate-With-Multi-Role-and-JWT#2]
Hi, great starting project!
i'm trying to connect from postman, but can't get the token to work.
/api/testSecurity and i add a "token" to params with the token i get from login
I always get "invalid token"

Thank you!

**Comment by SohanChy** [comment]
Thank you for your interest in the project,
I tried to follow conventions as much as I could in this boilerplate, so the token needs to be added to the HEADER, not params.

The key is `Authorization`,
Value is `Bearer abcdToken123`

Here is a sample screenshot of postman. Let me know if it works!
![image](https://user-images.githubusercontent.com/12531780/34461553-28c90a98-ee57-11e7-8f34-c90a1b0a8254.png)
@oterox

**Comment by oterox** [comment]
Hey,
i tried that before with no luck.
I get the token from http://api.oterox.science/api/login with user oterox and password oterox23

Now that i have the token i go to http://api.oterox.science/api/me with no luck
![api](https://user-images.githubusercontent.com/1680006/34461568-b7e91094-ee2d-11e7-9e8d-82cf2f23a923.jpg)

You're also getting a "token_invalid" message ;)

**Comment by SohanChy** [comment]
And as for your first (now edited out :D ) question, 
You can use Laravel Tinker.
`php artisan tinker`

Then 
```
$user = User::create([
                 'name' => "John Doe",
                 'username' => "username123",
                 'phone' => "0123456789",
                 'bio' => "I am a human",
                 'password' => bcrypt("hunter2")]
         );
```
Should create you a new user.

**Comment by oterox** [comment]
I didn't used Tinker, looks great. I generated other users "manually"

What i see is that your postman test failed too, right?

**Comment by SohanChy** [comment]
The screenshot was from a failed testcase from some time ago, I'm looking into it.
This boilerplate is currently at production in at least 3 projects, 1 of them is quite large, So your issue frightens me.

**Comment by SohanChy** [comment]
I just reproduced the problem, thanks for notifying me. This issue does NOT seem to exist on my deployed projects, I will have to check what is going on. Expect a response very soon. :)

**Comment by oterox** [comment]
Great, i hope you can fix it. The projecy is very usefull!!!
Any intention to add a roles table? It would be super!

Thanks again for your help

**Comment by SohanChy** [comment]
@iam-raihan Could you commits have caused this? Because none of my projects have those commits and they do not show this issue.

**Comment by SohanChy** [comment]
Ok, Finally found the issue and the fix is easy!
When you ran: 
`php artisan jwt:generate`
You got something like: 
`jwt-auth secret [abcd123] set successfully.`
But it did not actually add that key to your .env file due to a bug in the new official JWT AUTH Package.
It's an issue with recent versions of [JWT AUTH](https://github.com/tymondesigns/jwt-auth) itself, thats why I did not face it.
You can find the issue [here](https://github.com/tymondesigns/jwt-auth/issues/1425).
This package is widely used for JWT and none of those projects will work if updated :(
I hope they fix it soon.

Temporary Solution:
Run: `php artisan jwt:generate`
Copy the `secret [abcd123]` part,
Open .env file and add to end:
`JWT_SECRET=abcd123`

And it will start working (You need to login again and get new a token) :)
@oterox 
And yes, a role table is literally the very next thing that I want to add to this project the next time I have some free time on my hand. If you can do it, please do and open a PR.

**Comment by oterox** [comment]
Awesome, now it works!!!

Happy new year sohanchy

**Comment by SohanChy** [comment]
Happy new year! @oterox
